### ISSUE TITLE
error

### ISSUE THREAD

**Issue by guilhermeow** [Vezqi/Discrim-Bot#10]

**Comment by davdavdavdavdavdav** [comment]
If you still care the fix is really easy, change bot.username.discriminator to bot.user.discriminator

**Comment by Oscar47-GitHub** [comment]
i keep getting this
and no - the token isn't wrong
![image](https://user-images.githubusercontent.com/61665829/109688654-6f654100-7b7c-11eb-8440-ee0be746d80d.png)
